=== Jasig/uPortal/uportal-impl/src/main/resources/properties/chanpub/chandefs/channelDefinition.dtd
<!--
Copyright (c) 2003 The JA-SIG Collaborative.  All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in
   the documentation and/or other materials provided with the
   distribution.

3. Redistributions of any form whatsoever must retain the following
   acknowledgment:
   "This product includes software developed by the JA-SIG Collaborative
   (http://www.jasig.org/)."

THIS SOFTWARE IS PROVIDED BY THE JA-SIG COLLABORATIVE "AS IS" AND ANY
EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE JA-SIG COLLABORATIVE OR
ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

Author: Freddy Lopez, flopez@unicon.net
Author: Ken Weiner, kweiner@unicon.net
$Revision: 36666 $
-->

<!ELEMENT channel-definition (channelId?,title, name, fname, desc, type, class, timeout, hasedit, hashelp, hasabout, secure, locale, categories, groups, users?, parameters?, makeFNameAccessibleOnly? )>

<!ELEMENT categories (category)*>

<!ELEMENT groups (group)*>

<!ELEMENT users (user)*>

<!ELEMENT parameters (parameter)*>

<!ELEMENT parameter (name, value, description, ovrd)>

<!ELEMENT makeFNameAccessibleOnly EMPTY>
<!ELEMENT channelId (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT timeout (#PCDATA)>
<!ELEMENT hasedit (#PCDATA)>
<!ELEMENT hashelp (#PCDATA)>
<!ELEMENT hasabout (#PCDATA)>
<!ELEMENT secure (#PCDATA)>
<!ELEMENT locale (#PCDATA)>

<!ELEMENT category (#PCDATA)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT user (#PCDATA)>

<!ELEMENT value (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT ovrd (#PCDATA)>

=== Jasig/uPortal/properties/chanpub/render-count-portlet.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE channel-definition SYSTEM "channelDefinition.dtd">

<!--
 | This channel publishing fragment defines a channel for the
 | Render Count portlet, an example JSR-168 that exercises the
 | dynamic portlet title feature. 
 +-->
 
<channel-definition>

    <title>Render Count Portlet</title>
    <name>Render Count Portlet</name>
    <fname>render-count-portlet</fname>
    <desc>Demonstrates dynamic portlet titles.</desc>
    <type>Portlet</type>
    <class>org.jasig.portal.channels.portlet.CPortletAdapter</class>
    <timeout>60000</timeout>
    
    <hasedit>N</hasedit>
    <hashelp>N</hashelp>
    <hasabout>N</hasabout>

    <secure>N</secure>
    <locale>en_US</locale>
    
    <categories>
        <category>Development</category>
    </categories>
    
    <groups>
        <group>Everyone</group>
    </groups>
    
    <parameters>

        <!-- The syntax of the ID is [portlet-context-name].[portlet-name] -->
        <parameter>
            <name>portletDefinitionId</name>
            <value>RenderCountPortlet.RenderCount</value>
            <description>Identifies the portlet deployed within the portlet container</description>
            <ovrd>N</ovrd>
        </parameter>
        
    </parameters>
    
</channel-definition>

=== Jasig/uPortal/properties/chanpub/rss.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE channel-definition SYSTEM "channelDefinition.dtd">

<!--
 | End-user configured RSS reader.
 +-->
<channel-definition>

    <title>RSS Reader</title>
    <name>RSS Reader</name>
    <fname>rss-reader</fname>
    <desc>An end-user-configurable channel for reading RSS feeds.</desc>
    <type>User configured RSS</type>
    <class>org.jasig.portal.channels.CGenericXSLT</class>
    <timeout>5000</timeout>
    
    <hasedit>N</hasedit>
    <hashelp>N</hashelp>
    <hasabout>N</hasabout>

    <secure>N</secure>
    <locale>en_US</locale>
    
    <categories>
        <category>News</category>
    </categories>
    
    <groups>
        <group>Everyone</group>
    </groups>
    
    <parameters>
        
        <!-- The syntax of the ID is [portlet-context-name].[portlet-name] -->
        <parameter>
            <name>xmlUri</name>
            <value>set URL</value>
            <description>URL of the RSS feed</description>
            <!-- Y indicates the end user can override it -->
            <ovrd>Y</ovrd>
        </parameter>
        <parameter>
            <name>sslUri</name>
            <value>CGenericXSLT/RSS/RSS-universal.ssl</value>
            <description>Stylesheet selector for rendering RSS</description>
            <!-- set once centrally -->
            <ovrd>N</ovrd>
        </parameter>
        <parameter>
            <name>includeRssTitle</name>
            <value>false</value>
            <description>Display the title provided in the feed content</description>
            <!-- end users can choose-->
            <ovrd>Y</ovrd>
        </parameter>
        <parameter>
            <name>viewNum</name>
            <value>5</value>
            <description>How many items to show.</description>
            <!-- end users can choose -->
            <ovrd>Y</ovrd>
        </parameter>
        
    </parameters>
    
</channel-definition>
