=== Jasig/uPortal/uportal-impl/src/test/resources/org/jasig/portal/layout/simple/userLayout.dtd
<!--
Copyright 2001 The JA-SIG Collaborative.  All rights reserved.
See license distributed with this file and
available online at http://www.uportal.org/license.html

Author: John Laker, jlaker@udel.edu
$Revision$
-->

<!ELEMENT layout (folder|channel)*>
<!ELEMENT layout_fragment (folder|channel)*>

<!ATTLIST layout
  ID ID #REQUIRED>

<!ELEMENT folder (folder|channel)*>
<!ATTLIST folder
  ID ID #REQUIRED
  type (header|footer|regular) "regular"
  hidden (true|false) "false"
  unremovable (true|false) "false"
  immutable (true|false) "false"
  name CDATA #IMPLIED>


<!ELEMENT channel (parameter)*>
<!ATTLIST channel
  ID ID #REQUIRED
  name CDATA #REQUIRED
  description CDATA #REQUIRED
  title CDATA #REQUIRED
  class CDATA #REQUIRED
  chanID CDATA #REQUIRED
  typeID CDATA #REQUIRED
  fname CDATA #IMPLIED
  timeout CDATA "10000"
  unremovable (true|false) "false"
  immutable (true|false) "false"
  hidden (true|false) "false"
  editable (true|false) "false"
  hasHelp (true|false) "false"
  hasAbout (true|false) "false">


<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
  name CDATA #REQUIRED
  value CDATA #REQUIRED
  override (yes|no) "no">

=== Jasig/uPortal/uportal-impl/src/test/resources/org/jasig/portal/layout/simple/userLayout.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE greeting SYSTEM "userLayout.dtd">

<!--
This sample layout fragment is seriously broken.  It
does not reflect changes to layout structure as of approximately
uPortal 2.2 that introduced a single child folder element under the root
layout element.

CVS Metadata:
$Revision$ $Date$

-->

<layout ID="root">
    <folder ID="s1" hidden="false" immutable="false" name="Header folder"
        type="header" unremovable="false">
        <channel ID="n2" chanID="10"
            class="org.jasig.portal.channels.CHeader"
            description="uPortal Header channel" editable="false"
            fname="" hasAbout="false" hasHelp="false" hidden="false"
            immutable="true" name="Header" timeout="10000"
            title="Header" typeID="-1" unremovable="true"/>
        <channel ID="n3" chanID="99"
            class="org.jasig.portal.channels.CLogin"
            description="uPortal Login Channel" editable="false"
            fname="" hasAbout="true" hasHelp="true" hidden="false"
            immutable="true" name="Login" timeout="10000" title="Login"
            typeID="-1" unremovable="true"/>
    </folder>
    <folder ID="s4" hidden="false" immutable="true" name="Main"
        type="regular" unremovable="true" >
        <folder ID="s5" hidden="false" immutable="true" name="Column 1"
            type="regular" unremovable="true" >
            <channel ID="n6" chanID="5"
                class="org.jasig.portal.channels.CGenericXSLT"
                description="uPortal Demos channel" editable="false"
                fname="" hasAbout="false" hasHelp="false" hidden="false"
                immutable="true" name="uPortal-Powered Sites"
                timeout="10000" title="uPortal-Powered Sites" typeID="0" unremovable="true">
                <parameter name="xmlUri" value="http://www.interactivebusiness.com/publish/jasigPortalDemos.rss"/>
                <parameter name="sslUri" value="CGenericXSLT/RSS/RSS-0_9x.ssl"/>
            </channel>
        </folder>
        <folder ID="s7" hidden="false" immutable="false" name="Column 2"
            type="regular" unremovable="true" >
            <channel ID="n8" chanID="8"
                class="org.jasig.portal.channels.CInlineFrame"
                description="uPortal Home Page channel" editable="false"
                fname="" hasAbout="false" hasHelp="false" hidden="false"
                immutable="false" name="uPortal Home Page"
                timeout="20000" title="uPortal Home Page" typeID="2" unremovable="true">
                <parameter name="url" value="http://mis105.mis.udel.edu/ja-sig/uportal/"/>
                <parameter name="height" value="800"/>
            </channel>
        </folder>
    </folder>
    <folder ID="s9" hidden="false" immutable="false" name="Misc"
        type="regular" unremovable="true" >
        <folder ID="s10" hidden="false" immutable="false" name="Column 1"
            type="regular" unremovable="true" >
            <channel ID="n11" chanID="9"
                class="org.jasig.portal.channels.CApplet"
                description="Minesweeper applet" editable="false"
                fname="" hasAbout="false" hasHelp="false" hidden="false"
                immutable="true" name="Minesweeper" timeout="10000"
                title="Minesweeper" typeID="-1" unremovable="true">
                <parameter name="code" value="jmapplet.class"/>
                <parameter name="codeBase" value="http://www.nrr.co.uk/javamine"/>
                <parameter name="width" value="152"/>
                <parameter name="height" value="195"/>
                <parameter name="archive" value="javamine.jar"/>
                <parameter name="APPLET.type" value="application/x-java-applet"/>
                <parameter name="APPLET.level" value="beginner"/>
                <parameter name="APPLET.rows" value="8"/>
                <parameter name="APPLET.cols" value="8"/>
                <parameter name="APPLET.mines" value="10"/>
                <parameter name="APPLET.marks" value="true"/>
                <parameter name="APPLET.graphics" value="true"/>
            </channel>
        </folder>
        <folder ID="s12" hidden="false" immutable="true" name="Column 2"
            type="regular" unremovable="true" >
            <channel ID="n13" chanID="11"
                class="org.jasig.portal.channels.CGenericXSLT"
                description="Word of the Day channel" editable="false"
                fname="" hasAbout="false" hasHelp="false" hidden="false"
                immutable="true" name="Word of the Day" timeout="10000"
                title="Word of the Day" typeID="0" unremovable="true">
                <parameter name="xmlUri" value="http://www.dictionary.com/wordoftheday/wotd.rss"/>
                <parameter name="sslUri" value="CGenericXSLT/RSS/RSS-0_9x.ssl"/>
            </channel>
        </folder>
    </folder>
    <folder ID="s14" hidden="false" immutable="true" name="News"
        type="regular" unremovable="true" >
        <folder ID="s15" hidden="false" immutable="true" name="Column 1"
            type="regular" unremovable="true" >
            <channel ID="n16" chanID="12"
                class="org.jasig.portal.channels.CGenericXSLT"
                description="Salon.com channel" editable="false"
                fname="" hasAbout="false" hasHelp="false" hidden="false"
                immutable="true" name="Salon.com" timeout="10000"
                title="Salon.com" typeID="0" unremovable="true">
                <parameter name="xmlUri" value="http://www.salon.com/feed/RDF/salon_use.rdf"/>
                <parameter name="sslUri" value="CGenericXSLT/RSS/RSS-0_9x.ssl"/>
            </channel>
        </folder>
        <folder ID="s17" hidden="false" immutable="true" name="Column 2"
            type="regular" unremovable="true" >
            <channel ID="n18" chanID="6"
                class="org.jasig.portal.channels.CGenericXSLT"
                description="IBS News channel" editable="false" fname=""
                hasAbout="false" hasHelp="false" hidden="false"
                immutable="true" name="IBS News" timeout="10000"
                title="IBS News" typeID="0" unremovable="true">
                <parameter name="xmlUri" value="http://www.interactivebusiness.com/publish/ibs.rss"/>
                <parameter name="sslUri" value="CGenericXSLT/RSS/RSS-0_9x.ssl"/>
            </channel>
            <channel ID="n19" chanID="13"
                class="org.jasig.portal.channels.CGenericXSLT"
                description="Motley Fool channel" editable="false"
                fname="" hasAbout="false" hasHelp="false" hidden="false"
                immutable="true" name="The Motley Fool" timeout="10000"
                title="Motley Fool" typeID="0" unremovable="true">
                <parameter name="xmlUri" value="http://www.fool.com/xml/foolnews_rss091.xml"/>
                <parameter name="sslUri" value="CGenericXSLT/RSS/RSS-0_9x.ssl"/>
            </channel>
        </folder>
    </folder>
    <folder ID="s22" hidden="true" immutable="true"
        name="User Preferences" type="regular" unremovable="true" >
        <channel ID="n23" chanID="90"
            class="org.jasig.portal.channels.CChannelManager"
            description="Channel administration" editable="false"
            fname="portal/channelmanager/general" hasAbout="false"
            hasHelp="false" hidden="false" immutable="true"
            name="Channel Manager" timeout="30000"
            title="Channel Manager" typeID="-1" unremovable="true"/>
        <channel ID="n24" chanID="92"
            class="org.jasig.portal.channels.UserPreferences.CUserPreferences"
            description="User Preferences channel" editable="false"
            fname="portal/userpreferences/general" hasAbout="false"
            hasHelp="false" hidden="false" immutable="true"
            name="User Preferences" timeout="10000"
            title="User Preferences" typeID="-1" unremovable="true"/>
    </folder>
    <folder ID="s25" hidden="false" immutable="true"
        name="Footer folder" type="footer" unremovable="true" >
        <channel ID="n26" chanID="19"
            class="org.jasig.portal.channels.CGenericXSLT"
            description="uPortal Footer channel" editable="false"
            fname="" hasAbout="false" hasHelp="false" hidden="false"
            immutable="true" name="Footer" timeout="10000"
            title="Footer" typeID="1" unremovable="true">
            <parameter name="xmlUri" value="CGenericXSLT/emptyDocument.xml"/>
            <parameter name="sslUri" value="CGenericXSLT/footer/footer.ssl"/>
            <parameter name="cacheTimeout" value="3600"/>
        </channel>
    </folder>
</layout>
