=== Jasig/uPortal/uportal-war/src/main/webapp/dtd/PAGSGroupStore.dtd
<!--
Copyright (c) 2004 The JA-SIG Collaborative.  All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in
   the documentation and/or other materials provided with the
   distribution.
   
3. Redistributions of any form whatsoever must retain the following
   acknowledgment:
   "This product includes software developed by the JA-SIG Collaborative
   (http://www.jasig.org/)."
   
THIS SOFTWARE IS PROVIDED BY THE JA-SIG COLLABORATIVE "AS IS" AND ANY
EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE JA-SIG COLLABORATIVE OR
ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

Author: Dan Ellentuck, de3@columbia.edu
$Revision$

-->

<!-- A Group-Store is made up of 0 or more groups. -->
<!ELEMENT Group-Store (group*)>

<!ELEMENT group (group-key,group-name,group-description,selection-test?,members?)>
<!-- A group key must be unique within the document.  A group-name need not be. -->

<!ELEMENT group-key (#PCDATA)>
<!ELEMENT group-name (#PCDATA)>
<!ELEMENT group-description (#PCDATA)>

<!ELEMENT selection-test (test-group+)>
<!-- 
  A selection-test element determines if a person is a member of a group.  It is 
  composed of one or more test-group elements whose results are OR-ed together. 
  If a group does not contain a selection-test, it may have member groups but not
  member entities.  
-->

<!ELEMENT test-group (test+)>
<!-- 
  A test-group element is made up of 1 or more test elements whose results are 
  AND-ed together.  
-->

<!ELEMENT test (attribute-name,tester-class,test-value)>
<!-- 
  A test element contains the name of the attribute whose value is to be tested
  (attribute-name), the class that is to perform the test (tester-class), and the 
  value to be compared to the attribute value (test-value).   
-->
<!ELEMENT attribute-name (#PCDATA)>
<!ELEMENT tester-class (#PCDATA)>
<!ELEMENT test-value (#PCDATA)>

<!ELEMENT members (member-key*)>
<!-- The optional members element contains keys of member groups. -->
<!ELEMENT member-key (#PCDATA)>

=== Jasig/uPortal/uportal-impl/src/main/resources/properties/groups/PAGSGroupStoreConfig.xml
<?xml version="1.0"?>
<!DOCTYPE Group-Store PUBLIC "-//uPortal//PAGSGroupStore/EN" "PAGSGroupStore.dtd">

<!--
    PAGSGroupStoreConfig.xml is used to configure the person attributes group store.
    See PAGSGroupStore.dtd for xml grammar.

    To control the attributes that are available, see ../personDirectory.xml.

    Author: Dan Ellentuck, de3@columbia.edu
    Version $Revision$

    This sample configuration sets up 4 groups in the following relationship:

    All (0)
     |- Users (1)
     |- Short First Names (2)
         |- Ds and Staff (3)

    that is, Users (1) and Short First Names (2) are members of All (0), and Ds and Staff
    is a member of Short First Names (2).  These declarations can be used to assess group
    membership for the 6 users delivered in the base code (demo, student, etc.)

-->


<Group-Store>

<!-- Group declarations: -->

<!--
  Group 0: "PAGS Root"
-->
  <group>
    <group-key>0</group-key>
    <group-name>PAGS Root</group-name>
    <group-description>Root group for all PAGS groups.  Convenience for adding PAGS groups to a local group.</group-description>
    <members>
      <member-key>1</member-key>
      <member-key>2</member-key>
    </members>
  </group>


<!--
  Group 1: "Users"
  sn EQ (ignore case) "User"
-->
  <group>
    <group-key>1</group-key>
    <group-name>Users</group-name>
    <group-description>Portal users whose last names equal User</group-description>
    <selection-test>
      <test-group>
        <test>
          <attribute-name>sn</attribute-name>
          <tester-class>org.jasig.portal.groups.pags.testers.StringEqualsIgnoreCaseTester</tester-class>
          <test-value>User</test-value>
        </test>
      </test-group>
    </selection-test>
  </group>


<!--
  Group 2: "Short First Names"
  givenName has 5 or fewer characters
-->
  <group>
    <group-key>2</group-key>
    <group-name>Short First Names</group-name>
    <group-description>Portal users whose first names are between 1 and 5 characters long</group-description>
    <selection-test>
      <test-group>
        <test>
          <attribute-name>givenName</attribute-name>
          <tester-class>org.jasig.portal.groups.pags.testers.RegexTester</tester-class>
          <test-value>^.{1,5}$</test-value>
        </test>
      </test-group>
    </selection-test>
    <members>
      <member-key>3</member-key>
    </members>
  </group>


<!--
  Group 3: "Ds and Students"
  givenName starts with D or equals "Student" since the results of the test-group elements are
  OR-ed together.  HOWEVER, since this group is a member of group 2, members of this group must
  also qualify as members of group 2, i.e., given name must have 5 or fewer characters.  As a
  result, Student User should not show up as a member.
-->
  <group>
    <group-key>3</group-key>
    <group-name>Ds and Students</group-name>
    <group-description>Portal users whose first names begin with D or equal Student</group-description>
    <selection-test>
      <test-group>
        <test>
          <attribute-name>givenName</attribute-name>
          <tester-class>org.jasig.portal.groups.pags.testers.RegexTester</tester-class>
          <test-value>^D.*$</test-value>
        </test>
      </test-group>
      <test-group>
        <test>
          <attribute-name>givenName</attribute-name>
          <tester-class>org.jasig.portal.groups.pags.testers.StringEqualsTester</tester-class>
          <test-value>Student</test-value>
        </test>
      </test-group>
    </selection-test>
  </group>



<!-- End Group declarations: -->

</Group-Store>
